export const app = {
  name: 'MastaSkillz'
};

// Mock database
export const db = {
  collection: () => ({
    doc: () => ({
      get: async () => ({ exists: false, data: () => ({}) }),
      set: async () => ({}),
      update: async () => ({})
    }),
    add: async () => ({ id: `mock_${Date.now()}` }),
    where: () => ({
      orderBy: () => ({
        get: async () => ({ 
          docs: [], 
          empty: true
        })
      })
    })
  })
};

// Mock storage
export const storage = {
  ref: () => ({
    put: async () => ({
      ref: {
        getDownloadURL: async () => "https://example.com/mock-url"
      }
    })
  })
};

// Mock authentication
export const auth = {
  currentUser: null,
  onAuthStateChanged: (callback) => {
    callback(null);
    return () => {};
  },
  signInWithEmailAndPassword: async () => ({ user: { uid: 'mock-user-id' } }),
  createUserWithEmailAndPassword: async () => ({ user: { uid: 'mock-user-id' } }),
  signOut: async () => {}
};

// Mock functions
export const functions = {
  httpsCallable: () => async () => ({ 
    data: {
      success: true,
      titles: ["Mock Title Suggestion"],
      summary: "Mock summary generated by AI",
      questions: [],
      translatedContent: {}
    }
  })
};

// Mock empty exports for all Firebase modules to satisfy imports
export const getFirestore = () => db;
export const getStorage = () => storage;
export const getAuth = () => auth;
export const getFunctions = () => functions;
export const collection = () => ({});
export const doc = () => ({});
export const addDoc = async () => ({ id: `mock_${Date.now()}` });
export const getDoc = async () => ({ exists: false, data: () => ({}) });
export const getDocs = async () => ({ docs: [] });
export const updateDoc = async () => {};
export const deleteDoc = async () => {};
export const query = () => ({});
export const where = () => ({});
export const orderBy = () => ({});
export const ref = () => ({});
export const uploadBytes = async () => ({});
export const getDownloadURL = async () => "https://example.com/mock-url";
export const httpsCallable = () => async () => ({});